# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ac72901c370af2044528719251e5ab63b5763ac5d48a6fca64c6eb590cee77ed89560106953e42b6666be063deb42d368fcbc3bcbb28300797b0cf8ea918955

test:
  secret_key_base: 7ae425eaee2450d1d2ac68e5c9b5e84c22a4d06d7ee3984cd330a2f25cab7dbd52c0efeb23e479691b6f611a18fe7e04f127615b85cbe023cab8a36746b4de4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
