require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AffiliationTypeLevelsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # AffiliationTypeLevel. As you add validations to AffiliationTypeLevel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AffiliationTypeLevelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all affiliation_type_levels as @affiliation_type_levels" do
      affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:affiliation_type_levels)).to eq([affiliation_type_level])
    end
  end

  describe "GET #show" do
    it "assigns the requested affiliation_type_level as @affiliation_type_level" do
      affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
      get :show, params: {id: affiliation_type_level.to_param}, session: valid_session
      expect(assigns(:affiliation_type_level)).to eq(affiliation_type_level)
    end
  end

  describe "GET #new" do
    it "assigns a new affiliation_type_level as @affiliation_type_level" do
      get :new, params: {}, session: valid_session
      expect(assigns(:affiliation_type_level)).to be_a_new(AffiliationTypeLevel)
    end
  end

  describe "GET #edit" do
    it "assigns the requested affiliation_type_level as @affiliation_type_level" do
      affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
      get :edit, params: {id: affiliation_type_level.to_param}, session: valid_session
      expect(assigns(:affiliation_type_level)).to eq(affiliation_type_level)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AffiliationTypeLevel" do
        expect {
          post :create, params: {affiliation_type_level: valid_attributes}, session: valid_session
        }.to change(AffiliationTypeLevel, :count).by(1)
      end

      it "assigns a newly created affiliation_type_level as @affiliation_type_level" do
        post :create, params: {affiliation_type_level: valid_attributes}, session: valid_session
        expect(assigns(:affiliation_type_level)).to be_a(AffiliationTypeLevel)
        expect(assigns(:affiliation_type_level)).to be_persisted
      end

      it "redirects to the created affiliation_type_level" do
        post :create, params: {affiliation_type_level: valid_attributes}, session: valid_session
        expect(response).to redirect_to(AffiliationTypeLevel.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved affiliation_type_level as @affiliation_type_level" do
        post :create, params: {affiliation_type_level: invalid_attributes}, session: valid_session
        expect(assigns(:affiliation_type_level)).to be_a_new(AffiliationTypeLevel)
      end

      it "re-renders the 'new' template" do
        post :create, params: {affiliation_type_level: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested affiliation_type_level" do
        affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
        put :update, params: {id: affiliation_type_level.to_param, affiliation_type_level: new_attributes}, session: valid_session
        affiliation_type_level.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested affiliation_type_level as @affiliation_type_level" do
        affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
        put :update, params: {id: affiliation_type_level.to_param, affiliation_type_level: valid_attributes}, session: valid_session
        expect(assigns(:affiliation_type_level)).to eq(affiliation_type_level)
      end

      it "redirects to the affiliation_type_level" do
        affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
        put :update, params: {id: affiliation_type_level.to_param, affiliation_type_level: valid_attributes}, session: valid_session
        expect(response).to redirect_to(affiliation_type_level)
      end
    end

    context "with invalid params" do
      it "assigns the affiliation_type_level as @affiliation_type_level" do
        affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
        put :update, params: {id: affiliation_type_level.to_param, affiliation_type_level: invalid_attributes}, session: valid_session
        expect(assigns(:affiliation_type_level)).to eq(affiliation_type_level)
      end

      it "re-renders the 'edit' template" do
        affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
        put :update, params: {id: affiliation_type_level.to_param, affiliation_type_level: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested affiliation_type_level" do
      affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
      expect {
        delete :destroy, params: {id: affiliation_type_level.to_param}, session: valid_session
      }.to change(AffiliationTypeLevel, :count).by(-1)
    end

    it "redirects to the affiliation_type_levels list" do
      affiliation_type_level = AffiliationTypeLevel.create! valid_attributes
      delete :destroy, params: {id: affiliation_type_level.to_param}, session: valid_session
      expect(response).to redirect_to(affiliation_type_levels_url)
    end
  end

end
